# Generated by Django 4.1.9 on 2023-05-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='user',
        ),
        migrations.AddField(
            model_name='transcript',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
    ]
