# Generated by Django 4.1.9 on 2023-06-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_remove_transcript_user_transcript_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='metadata_generated',
            field=models.BooleanField(default=False),
        ),
    ]
