# Generated by Django 4.1.9 on 2023-06-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0003_transcript_metadata_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_level',
            field=models.CharField(choices=[('project', 'Project level queries'), ('transcript', 'Transcript level queries')], default='transcript', max_length=32),
            preserve_default=False,
        ),
    ]
