# Generated by Django 4.1.9 on 2023-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0004_query_query_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeds',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('C', 'Completed'), ('F', 'Failed')], default='C', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synthesis',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('C', 'Completed'), ('F', 'Failed')], default='C', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='synthesis',
            name='output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synthesis',
            name='prompt',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
