# Generated by Django 4.1.9 on 2023-06-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0005_embeds_status_synthesis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
