version: "3.9"

services:
  web:
    build:
      context: ./web
      args:
        - DEV=true
    ports:
      - 8002:8002
    volumes:
      - ./web:/web
      - node-modules:/web/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/
      - VITE_ZOOM_CLIENT_ID=mTdoPcOmQAm54Fz1ZxL0oQ
      - VITE_ZOOM_REDIRECT_URL=http://localhost:8002/all-projects
      - VITE_ZOOM_SECRETS_BASE64=bVRkb1BjT21RQW01NEZ6MVp4TDBvUTpDUkJZeTJldzlqTllyN2Zybm52U1hLS2hET1hvcTlwOQ==
      - VITE_GOOGLE_CLIENT_ID = 1059206380136-aieu7ujj247n2lk4b8o4ju59sq14uvte.apps.googleusercontent.com
      - VITE_GOOGLE_CLIENT_SECRET = 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
      - VITE_GOOGLE_REDIRECT_URL = http://localhost
    env_file:
      - ./.env
    depends_on:
      - api

  api:
    build:
      context: ./api
      args:
        - DEV=true
    ports:
      - 8000:8000
      - 3000:3000 # for debugger
    volumes:
      - ./api:/api
      - dev-static-data:/vol/web
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - SYNTHESIS_URL=http://api_synthesis:8001
      - GCLOUD_EMULATOR_SERVICE_URL=http://api:8000
      - GCLOUD_EMULATOR_URL=gcloud-tasks-emulator:8123
      - DEBUG=1
    depends_on:
      - db
      - api_synthesis
      - gcloud-tasks-emulator

  api_synthesis:
    build:
      context: ./api-synthesis
      args:
        - DEV=true
    ports:
      - 8001:8001
      - 3001:3001 # for debugger
      - 3002:3002 # for debugger
    volumes:
      - ./api-synthesis:/api-synthesis
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123
    ports:
      - 8123:8123

volumes:
  dev-db-data:
  dev-static-data:
  node-modules:
