version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DEBUG=1
    depends_on:
      - db
      - redis

  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DEBUG=1
    depends_on:
      - db
      - redis
      - app

  redis:
    image: redis:7-alpine

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  dev-db-data:
  dev-static-data:
