version: "3.9"

x-logging-config: &logging-config
  logging:
    driver: gcplogs
    options:
      gcp-project: ${GCLOUD_PROJECT_ID}

services:

  web:
    <<: *logging-config
    build:
      context: ./web
    ports:
      - 8002:8002
    volumes:
      - ./web:/web
      - node-modules:/web/node_modules
    env_file:
      - ./.env
    environment:
      - VITE_API_URL=${API_SERVICE_URL}/
      - VITE_ZOOM_REDIRECT_URL=${WEB_SERVICE_URL}/all-projects
    depends_on:
      - api

  api:
    <<: *logging-config
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    env_file:
      - ./.env
    environment:
      - DEBUG=1
      - SYNTHESIS_URL=http://api_synthesis:8001
    depends_on:
      - api_synthesis

  api_synthesis:
    <<: *logging-config
    build:
      context: ./api-synthesis
    ports:
      - 8001:8001
    volumes:
      - ./api-synthesis:/api-synthesis
    env_file:
      - ./.env
    environment:
      - DEBUG=1

  proxy:
    <<: *logging-config
    build:
      context: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    environment:
      - WEB_HOST=web:8002
      - API_HOST=api:8000
    depends_on:
      - api

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  node-modules: