version: "3.9"

services:
  web:
    build:
      context: ./web
      args:
        - DEV=true
    ports:
      - 8002:8002
    volumes:
      - ./web:/web
      - node-modules:/web/node_modules
    environment:
      - DEBUG=1
    env_file:
      - ./.env
    depends_on:
      - api
      - gcloud-tasks-emulator

  api:
    build:
      context: ./api
      args:
        - DEV=true
    ports:
      - 8000:8000
      - 3000:3000 # for debugger
    volumes:
      - ./api:/api
      - dev-static-data:/vol/web
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - SYNTHESIS_URL=http://api_synthesis:8001
      - GCLOUD_EMULATOR_SERVICE_URL=http://api:8000
      - GCLOUD_EMULATOR_URL=gcloud-tasks-emulator:8123
      - DEBUG=1
    depends_on:
      - db
      - api_synthesis

  api_synthesis:
    build:
      context: ./api-synthesis
      args:
        - DEV=true
    ports:
      - 8001:8001
      - 3001:3001 # for debugger
      - 3002:3002 # for debugger
    volumes:
      - ./api-synthesis:/api-synthesis
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123
    ports:
      - 8123:8123

volumes:
  dev-db-data:
  dev-static-data:
  node-modules:
