# Generated by Django 4.1.10 on 2023-07-25 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcript', '0006_transcript_end_time_transcript_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
            options={
                'verbose_name': 'Processed Transcript',
                'verbose_name_plural': 'Processed Transcripts',
            },
        ),
    ]
