FROM python:3.9.15
LABEL maintainer="getmetanext.com"

ENV PYTHONNUNBUFFERED 1
WORKDIR /api-synthesis

COPY . /api-synthesis

ARG DEV=false

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    /py/bin/pip install --no-cache-dir --upgrade -r /api-synthesis/requirements.txt && \
    if [ $DEV = "true" ]; \
        then /py/bin/pip install --no-cache-dir --upgrade -r /api-synthesis/requirements.dev.txt ; \
    fi && \
    chmod +x /api-synthesis/run.sh

EXPOSE 8001

ENV PATH="/py/bin:$PATH"

CMD ["/api-synthesis/run.sh"]
