FROM nginxinc/nginx-unprivileged:1-alpine
LABEL maintainer="getmetanext.com"

COPY ./default.conf.tpl /etc/nginx/default.conf.tpl
COPY ./uwsgi_params /etc/nginx/uwsgi_params
COPY ./run.sh /run.sh

ENV LISTEN_PORT=9000
ENV API_HOST=api
ENV API_PORT=8000
ENV WEB_HOST=web
ENV WEB_PORT=8002

USER root

RUN touch /etc/nginx/conf.d/default.conf && \
    chown nginx:nginx /etc/nginx/conf.d/default.conf && \
    chmod +x /run.sh

USER nginx

CMD ["/run.sh"]