FROM nginxinc/nginx-unprivileged:1-alpine
LABEL maintainer="getmetanext.com"

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./uwsgi_params /etc/nginx/uwsgi_params
COPY ./run.sh /run.sh

USER root

RUN chmod +x /run.sh

CMD ["/run.sh"]
