# Generated by Django 4.1.8 on 2023-04-12 20:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('interviewee_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('interviewer_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('transcript', models.TextField(blank=True, max_length=100000, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('SM', 'Summary'), ('CS', 'Concise')], max_length=2)),
                ('output', models.JSONField(blank=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
            options={
                'verbose_name': 'Synthesis',
                'verbose_name_plural': 'Syntheses',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=10000)),
                ('output', models.JSONField(blank=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='Embeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
            options={
                'verbose_name': 'Embeds',
                'verbose_name_plural': 'Embeds',
            },
        ),
    ]
