# Generated by Django 4.1.7 on 2023-03-08 22:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('interviewee_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('interviewer_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('transcript', models.TextField(blank=True, max_length=100000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AISynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('SM', 'Summary'), ('CS', 'Concise')], max_length=2)),
                ('output', models.TextField(blank=True, max_length=100000, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('tokens_used', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
            options={
                'verbose_name': 'AI Synthesis',
                'verbose_name_plural': 'AI Syntheses',
            },
        ),
        migrations.CreateModel(
            name='AIChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('SM', 'Summary'), ('CS', 'Concise')], max_length=2)),
                ('chunks', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=10000), size=None)),
                ('chunks_processed', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=10000), size=None)),
                ('model_name', models.CharField(max_length=255)),
                ('tokens_used', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
            options={
                'verbose_name': 'AI Chunks',
                'verbose_name_plural': 'AI Chunks',
            },
        ),
    ]
