# Generated by Django 4.1.7 on 2023-03-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichunks',
            name='model_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aisynthesis',
            name='model_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
