# Generated by Django 4.1.7 on 2023-02-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='transcript',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
