# Generated by Django 4.1.7 on 2023-03-10 04:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_alter_aichunks_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AIEmbeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunks', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=10000), size=None)),
                ('index_name', models.CharField(max_length=255)),
                ('index_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
            options={
                'verbose_name': 'AI Embeds',
                'verbose_name_plural': 'AI Embeds',
            },
        ),
    ]
