# Generated by Django 4.1.7 on 2023-02-28 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_alter_transcript_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('SM', 'Summary'), ('HL', 'Highlights'), ('CS', 'Concise')], max_length=2)),
                ('output', models.TextField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transcript',
            name='summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript', to='transcript.aisynthesis'),
        ),
    ]
