# Generated by Django 4.1.7 on 2023-03-02 07:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0003_aisynthesis_transcript_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_groups', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=10000), size=None)),
                ('para_group_summaries', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=10000), size=None)),
            ],
            options={
                'verbose_name': 'Processed Chunk',
                'verbose_name_plural': 'Processed Chunks',
            },
        ),
        migrations.AlterModelOptions(
            name='aisynthesis',
            options={'verbose_name': 'AI Synthesis', 'verbose_name_plural': 'AI Syntheses'},
        ),
        migrations.AddField(
            model_name='transcript',
            name='chunks',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript', to='transcript.processedchunks'),
        ),
    ]
