# Generated by Django 4.1.7 on 2023-03-11 03:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0003_transcript_cost_alter_transcript_title_aiembeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=10000)),
                ('result', models.TextField(max_length=10000)),
                ('search_values', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=10000), size=None)),
                ('search_scores', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10), size=None)),
                ('query_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
