# Generated by Django 4.1.7 on 2023-03-02 22:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0004_processedchunks_alter_aisynthesis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisynthesis',
            name='tokens_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedchunks',
            name='tokens_used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcript',
            name='summary_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
