# Generated by Django 4.1.9 on 2023-05-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcript', '0002_remove_transcript_user_transcript_project'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_email', models.EmailField(max_length=1024)),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
                ('meeting_app', models.CharField(choices=[('zoom', 'Zoom meeting app')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingBot',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('joining_call', 'Joining call'), ('in_waiting_room', 'In waiting room'), ('in_call_not_recording', 'Not recording'), ('in_call_recording', 'Call recording'), ('call_ended', 'Transcription Complete'), ('done', 'Video available for download'), ('fatal', 'Error'), ('analysis_done', 'Async Intelligence done')], max_length=32)),
                ('message', models.CharField(max_length=1024, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('transcript', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
        ),
        migrations.AddConstraint(
            model_name='meetingapp',
            constraint=models.UniqueConstraint(fields=('meeting_email', 'meeting_app'), name='unique_meeting_details'),
        ),
    ]
