# Generated by Django 4.1.9 on 2023-06-07 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0003_alter_meetingapp_meeting_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingapp',
            name='meeting_app',
            field=models.CharField(choices=[('zoom', 'Zoom meeting app')], max_length=32),
        ),
        migrations.CreateModel(
            name='MeetingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_app', models.CharField(choices=[('google', 'Google Calendar')], max_length=32)),
                ('calendar_id', models.CharField(max_length=512)),
                ('calendar_email', models.EmailField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='meetingcalendar',
            constraint=models.UniqueConstraint(fields=('calendar_email', 'calendar_app'), name='unique_calendar_details'),
        ),
    ]
