# Generated by Django 4.1.9 on 2023-06-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_meetingbot_end_time_meetingbot_meeting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbot',
            name='title',
            field=models.CharField(default='Meeting', max_length=512),
        ),
    ]
