# Generated by Django 4.1.10 on 2023-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_meetingbot_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingcalendar',
            name='calendar_app',
            field=models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook')], max_length=32),
        ),
    ]
