# Generated by Django 4.1.10 on 2023-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_alter_meetingcalendar_calendar_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcalendar',
            name='access_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meetingcalendar',
            name='refresh_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
