# Generated by Django 4.1.10 on 2023-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_alter_meetingcalendar_calendar_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcalendar',
            name='access_token',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='meetingcalendar',
            name='refresh_token',
            field=models.TextField(default=None),
        ),
    ]
