# Generated by Django 4.1.8 on 2023-04-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
            ],
        ),
    ]
