# Generated by Django 4.1.8 on 2023-04-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
        ('meetingbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingbot',
            name='transcript',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript'),
        ),
    ]
