# Generated by Django 4.1.8 on 2023-04-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingbot', '0002_alter_meetingbot_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingbot',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
