# Generated by Django 4.1.8 on 2023-04-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingbot', '0003_alter_meetingbot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbot',
            name='message',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
