# Generated by Django 4.1.8 on 2023-04-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingbot', '0004_meetingbot_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingbot',
            name='message',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
