# Generated by Django 4.1.10 on 2023-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_name',
            field=models.CharField(default='LumianBot', max_length=255),
            preserve_default=False,
        ),
    ]
