# Generated by Django 4.1.10 on 2023-07-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_bot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_summary', models.CharField(choices=[('gpt-4', 'GPT 4'), ('gpt-3.5-turbo-16k', 'GPT 3.5')], default='gpt-3.5-turbo-16k', help_text='LLM used to generate summary.', max_length=32)),
                ('llm_concise', models.CharField(choices=[('gpt-4', 'GPT 4'), ('gpt-3.5-turbo-16k', 'GPT 3.5')], default='gpt-3.5-turbo-16k', help_text='LLM used to generate concise summaries.', max_length=32)),
                ('llm_query', models.CharField(choices=[('gpt-4', 'GPT 4'), ('gpt-3.5-turbo-16k', 'GPT 3.5')], default='gpt-3.5-turbo-16k', help_text='LLM used to respond to queries.', max_length=32)),
                ('indexed_line_min_chars', models.IntegerField(default=90)),
                ('chunk_min_tokens_summary', models.IntegerField(default=2000)),
                ('chunk_min_tokens_concise', models.IntegerField(default=2000)),
                ('chunk_min_tokens_query', models.IntegerField(default=400)),
                ('max_input_tokens_summary', models.IntegerField(default=2500)),
                ('max_input_tokens_concise', models.IntegerField(default=2500)),
                ('max_input_tokens_query', models.IntegerField(default=3400)),
                ('max_input_tokens_metadata', models.IntegerField(default=3600)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
