# Generated by Django 4.1.10 on 2023-07-25 21:11

from django.db import migrations


def create_default_settings(apps, schema_editor):
    AppSettings = apps.get_model('core', 'AppSettings')
    default_settings = AppSettings()
    default_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appsettings'),
    ]

    operations = [
        migrations.RunPython(create_default_settings),
    ]
