# Generated by Django 4.1.10 on 2023-07-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_appsettings_llm_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='llm_concise',
            field=models.CharField(blank=True, default='gpt-3.5-turbo-16k', help_text='LLM used to generate concise transcripts. Leave blank to use values in environment vars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='llm_metadata',
            field=models.CharField(blank=True, default='gpt-3.5-turbo-16k', help_text='LLM used to generate metadata. Leave blank to use values in environment vars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='llm_query',
            field=models.CharField(blank=True, default='gpt-3.5-turbo-16k', help_text='LLM used to respond to queries. Leave blank to use values in environment vars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='llm_summary_chunk',
            field=models.CharField(blank=True, default='gpt-3.5-turbo-16k', help_text='LLM used to generate summary for a chunk. Leave blank to use values in environment vars.', max_length=255),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='llm_summary_final',
            field=models.CharField(blank=True, default='gpt-3.5-turbo-16k', help_text='LLM used to generate final summary. Leave blank to use values in environment vars.', max_length=255),
        ),
    ]
