FROM python:3.9-alpine3.13
LABEL maintainer="getmetanext.com"

ENV PYTHONNUNBUFFERED 1
WORKDIR /api

COPY . /api

EXPOSE 8000

ARG DEV=false

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --update --no-cache postgresql-client jpeg-dev && \
    apk add --update --no-cache --virtual .tmp-build-deps \
        build-base postgresql-dev musl-dev zlib zlib-dev linux-headers && \
    /py/bin/pip install -r /api/requirements.txt && \
    if [ $DEV = "true" ]; \
        then /py/bin/pip install -r /api/requirements.dev.txt ; \
    fi && \
    apk del .tmp-build-deps && \
    adduser \
        --disabled-password \
        --no-create-home \
        django-user && \
    mkdir -p /vol/web/media && \
    mkdir -p /vol/web/static && \
    chown -R django-user:django-user /vol && \
    chmod -R 755 /vol

USER django-user

ENV PATH="/py/bin:$PATH"
