---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: >
          docker-compose run --rm app sh -c "
          export OPENAI_ORG_ID=\"${{ secrets.OPENAI_ORG_ID }}\" &&
          export OPENAI_API_KEY=\"${{ secrets.OPENAI_API_KEY }}\" &&
          export PINECONE_API_KEY=\"${{ secrets.PINECONE_API_KEY }}\" &&
          python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
