---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Test App
        run: >
          docker-compose run --rm app sh -c "
          export TEST_ENV=\"$TEST_ENV\" &&
          python manage.py wait_for_db && python manage.py test"
      - name: Test Synthesis
        run: >
          docker-compose run --rm app_synthesis sh -c "
          export TEST_ENV=\"$TEST_ENV\" &&
          PYTHONPATH=. python commands/wait_for_db.py &&
          PYTHONPATH=. pytest tests"
      - name: Lint App
        run: docker-compose run --rm app sh -c "flake8"
      - name: Lint Synthesis
        run: docker-compose run --rm app_synthesis sh -c "flake8"
